# Default values for helmv2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
repository:
  image: acrreplace.azurecr.io/devopsoh/imagereplace
  tag: latest
  pullPolicy: Always
image:
  name: sentinel-api
  label: sentinel-api
  containerPort: 8080
service:
  externalPort: 80
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  rules:
    endpoint:
      host: changeme
      paths:
      - path: /api/sentinel
        serviceName: sentinel-api-svc
        servicePort: 80
      - path: /api/leaderboard/teams
        serviceName: sentinel-api-svc
        servicePort: 80
      - path: /api/leaderboard/challenges
        serviceName: sentinel-api-svc
        servicePort: 80
      - path: /api/leaderboard/challengeDefinitions
        serviceName: sentinel-api-svc
        servicePort: 80
      - path: /api/leaderboard/servicehealth
        serviceName: sentinel-api-svc
        servicePort: 80
      - path: /api/healthcheck/sentinel
        serviceName: sentinel-api-svc
        servicePort: 80
      - path: /api/auth/login
        serviceName: sentinel-api-svc
        servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
