# https://github.com/kubernetes/charts/blob/master/stable/traefik/values.yaml
## Default values for Traefik
imageTag: 1.6-alpine
externalTrafficPolicy: Local
replicas: 1
debug:
  enabled: true
deploymentStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
ssl:
  enabled: true
  enforced: false
  insecureSkipVerify: true
  persistence:
    enabled: true
    annotations: {}
    storageClass: "default"
    accessMode: ReadWriteOnce
    size: 1Gi
dashboard:
  enabled: true
  domain: akstraefikreplaceme.locationreplace.cloudapp.azure.com
service:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: akstraefikreplaceme
rbac:
  enabled: true
## Enable the /metrics endpoint, for now only supports prometheus
## set to true to enable metric collection by prometheus
metrics:
  prometheus:
    enabled: true