{{- range $i, $e := until (.Values.teams.totalNumber|int) }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Values.teams.baseName }}{{ add1 $i }}-user
spec:
  containers:
  - name: {{ $.Values.teams.baseName }}{{ add1 $i }}-user
    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
    imagePullPolicy: {{ $.Values.image.pullPolicy }}
    env:
    - name: SENTINEL_TEAM_ID
      value: {{ $.Values.teams.baseName }}{{ add1 $i }}
    - name: SENTINEL_SERVICE_ID
      value: {{ $.Values.teams.baseName }}{{ add1 $i }}user
    - name: SENTINEL_ENDPOINT
      value: "http://akstraefik{{ $.Values.teams.baseName }}{{ add1 $i }}.{{ $.Values.teams.location }}.cloudapp.azure.com/api/healthcheck/user"
    - name: SENTINEL_PORT
      value: "{{ $.Values.services.port }}"
    - name: SENTINEL_API_URL
      value: "{{ $.Values.teams.apiUrl }}"
    - name: SENTINEL_POLLING_INTERVAL
      value: "{{ $.Values.services.pollingInterval }}"
    - name: SENTINEL_RETRY_DURATION
      value: "{{ $.Values.services.retryDuration }}"
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Values.teams.baseName }}{{ add1 $i }}-trip
spec:
  containers:
  - name: {{ $.Values.teams.baseName }}{{ add1 $i }}-trip
    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
    imagePullPolicy: {{ $.Values.image.pullPolicy }}
    env:
    - name: SENTINEL_TEAM_ID
      value: {{ $.Values.teams.baseName }}{{ add1 $i }}
    - name: SENTINEL_SERVICE_ID
      value: {{ $.Values.teams.baseName }}{{ add1 $i }}trip
    - name: SENTINEL_ENDPOINT
      value: "http://akstraefik{{ $.Values.teams.baseName }}{{ add1 $i }}.{{ $.Values.teams.location }}.cloudapp.azure.com/api/healthcheck/trips"
    - name: SENTINEL_PORT
      value: "{{ $.Values.services.port }}"
    - name: SENTINEL_API_URL
      value: "{{ $.Values.teams.apiUrl }}"
    - name: SENTINEL_POLLING_INTERVAL
      value: "{{ $.Values.services.pollingInterval }}"
    - name: SENTINEL_RETRY_DURATION
      value: "{{ $.Values.services.retryDuration }}"
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Values.teams.baseName }}{{ add1 $i }}-poi
spec:
  containers:
  - name: {{ $.Values.teams.baseName }}{{ add1 $i }}-poi
    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
    imagePullPolicy: {{ $.Values.image.pullPolicy }}
    env:
    - name: SENTINEL_TEAM_ID
      value: {{ $.Values.teams.baseName }}{{ add1 $i }}
    - name: SENTINEL_SERVICE_ID
      value: {{ $.Values.teams.baseName }}{{ add1 $i }}poi
    - name: SENTINEL_ENDPOINT
      value: "http://akstraefik{{ $.Values.teams.baseName }}{{ add1 $i }}.{{ $.Values.teams.location }}.cloudapp.azure.com/api/healthcheck/poi"
    - name: SENTINEL_PORT
      value: "{{ $.Values.services.port }}"
    - name: SENTINEL_API_URL
      value: "{{ $.Values.teams.apiUrl }}"
    - name: SENTINEL_POLLING_INTERVAL
      value: "{{ $.Values.services.pollingInterval }}"
    - name: SENTINEL_RETRY_DURATION
      value: "{{ $.Values.services.retryDuration }}"
{{- end }}