image:
  repository: sentinel
  tag: latest
  pullPolicy: IfNotPresent
services:
  port: 80
  pollingInterval: 30
  retryDuration: 3
teams:
  totalNumber: 1
  baseName: devopsoh
  location: eastus
  apiUrl: https://changeme.azurewebsites.net # Azure Functions API where the health events get logged through