apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.image.name }}-deploy"
  labels:
    deploy: {{ .Values.image.label }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.label }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.label }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.repository.image }}:{{ .Values.repository.tag }}"
        imagePullPolicy: {{ .Values.repository.pullPolicy }}
        name: {{ .Values.image.name }}
        ports:
          - containerPort: {{ .Values.image.containerPort }}
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
