apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.image.label }}
  ports:
    - protocol: TCP
      name: {{ .Values.image.name }}http
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.image.containerPort }}
    - protocol: TCP
      name: {{ .Values.image.name }}https
      port: 443
      targetPort: 443