apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.host.functionAppName }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      team: {{ $.Values.host.functionAppName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate      
  template:
    metadata:
      labels:
        team: {{ $.Values.host.functionAppName }}
    spec:
      containers:
      - name: {{ $.Values.host.functionAppName }}-app
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        env:
        - name: AzureWebJobsStorage
          valueFrom:
            secretKeyRef:
              name: storage
              key: connection_string
        - name: SqlConnectionString
          valueFrom:
            secretKeyRef:
              name: sql
              key: connection_string
