# Default values for helmv2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: team1acrxs76.azurecr.io/devopsoh/simulator
  tag: latest
  pullPolicy: Always
  pullSecrets: azureacr

#service:
#  name: pois-svc
#  type: ClusterIP
#  internalPort: 8080
#  externalPort: 8080

#ingress:
#  enabled: true
#  annotations:
#    kubernetes.io/ingress.class: traefik
#  path: /api/GetAllPOIs
#  hosts:
#    - mydriving-admin.julien.work
#  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
