trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      export AZDO_PERSONAL_ACCESS_TOKEN=$SYSTEM_ACCESSTOKEN
      export AZDO_ORG_SERVICE_URL=$(System.CollectionUri)

      echo ${AZDO_ORG_SERVICE_URL}
      echo ${AZDO_PERSONAL_ACCESS_TOKEN}
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: 'latest'

  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/provision-team/terraform-state/'
      allowTelemetryCollection: false

  - task: TerraformCLI@0
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/provision-team/terraform-state/'
      allowTelemetryCollection: false