trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: tfstate

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'AzureServiceConnection'
    backendAzureRmResourceGroupName: $(TFSTATE_RESOURCES_GROUP_NAME)
    backendAzureRmStorageAccountName: $(TFSTATE_STORAGE_ACCOUNT_NAME)
    backendAzureRmContainerName: $(TFSTATE_STORAGE_CONTAINER_NAME)
    backendAzureRmKey: $(TFSTATE_KEY)
    allowTelemetryCollection: true