trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  - group: tfstate
  - name: workDir
    value: '$(System.DefaultWorkingDirectory)/provision-team/terraform/'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'AzureServiceConnection'
    backendAzureRmResourceGroupName: $(TFSTATE_RESOURCES_GROUP_NAME)
    backendAzureRmStorageAccountName: $(TFSTATE_STORAGE_ACCOUNT_NAME)
    backendAzureRmContainerName: $(TFSTATE_STORAGE_CONTAINER_NAME)
    backendAzureRmKey: $(TFSTATE_KEY)
    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    workingDirectory: $(workDir)
    environmentServiceName: 'AzureServiceConnection'
    allowTelemetryCollection: true
    publishPlanResults: 'tfstate'
  env:
    AZDO_PERSONAL_ACCESS_TOKEN: $(System.AccessToken)
    AZDO_ORG_SERVICE_URL: $(System.CollectionUri)