trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    displayName: 'Terraform Install'
    inputs:
      terraformVersion: 'latest'
  - task: TerraformCLI@0
    displayName: 'Terraform Init'
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/provision-team/terraform-state/'
      allowTelemetryCollection: false
  - task: TerraformCLI@0
    displayName: 'Terraform Plan'
    inputs:
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/provision-team/terraform-state/'
      environmentServiceName: 'AzureServiceConnection'
      runAzLogin: true
      allowTelemetryCollection: false
    env:
      AZDO_PERSONAL_ACCESS_TOKEN: $(System.AccessToken)
      AZDO_ORG_SERVICE_URL: $(System.CollectionUri)
  - task: TerraformCLI@0
    displayName: 'Terraform Apply'
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/provision-team/terraform-state/'
      environmentServiceName: 'AzureServiceConnection'
      allowTelemetryCollection: false
    env:
      AZDO_PERSONAL_ACCESS_TOKEN: $(System.AccessToken)
      AZDO_ORG_SERVICE_URL: $(System.CollectionUri)