name: 'infra'

on:
  # push:
  #   branches:
  #   - main
  # pull_request:
  workflow_dispatch:

env:
  WORKDIR: 'provision-team/terraform'
  RESOURCES_PREFIX: ${{ secrets.RESOURCES_PREFIX }}
  LOCATION: ${{ secrets.LOCATION }}

jobs:
  infra:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKDIR }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare Azure Service Principals
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        export ARM_CLIENT_ID=$(echo "${AZURE_CREDENTIALS}" | jq -r ".clientId")
        export ARM_CLIENT_SECRET=$(echo "${AZURE_CREDENTIALS}" | jq -r ".clientSecret")
        export ARM_SUBSCRIPTION_ID=$(echo "${AZURE_CREDENTIALS}" | jq -r ".subscriptionId")
        export ARM_TENANT_ID=$(echo "${AZURE_CREDENTIALS}" | jq -r ".tenantId")

        echo "ARM_CLIENT_ID=${ARM_CLIENT_ID}" >> "${GITHUB_ENV}"
        echo "ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}" >> "${GITHUB_ENV}"
        echo "ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}" >> "${GITHUB_ENV}"
        echo "ARM_TENANT_ID=${ARM_TENANT_ID}" >> "${GITHUB_ENV}"

        echo "::add-mask::$ARM_CLIENT_SECRET"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init -backend-config=storage_account_name=${TFSTATE_STORAGE_ACCOUNT_NAME} -backend-config=container_name=${TFSTATE_STORAGE_CONTAINER_NAME} -backend-config=key=${TFSTATE_KEY} -backend-config=resource_group_name=${TFSTATE_RESOURCES_GROUP_NAME}
      env:
        TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}
        TFSTATE_STORAGE_CONTAINER_NAME: ${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}
        TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}
        TFSTATE_RESOURCES_GROUP_NAME: ${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}

    - name: Terraform Plan
      run: |      
        terraform plan -var="resources_prefix=${RESOURCES_PREFIX}" -var="location=${LOCATION}"

    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      # TODO: condition -> no run if tfplan no change
      run: |
        terraform apply -auto-approve -var="resources_prefix=${RESOURCES_PREFIX}" -var="location=${LOCATION}"